[Interface]
Address = 10.10.0.1/24
PrivateKey = OF9nbGvuLjPrGTNemHKXRIqepuw45JsHbujC2VkEY3A=
ListenPort = 51820

[Peer]
PublicKey = ZNtQsg2Bn0V9bDtrn3aKsRKKw4P/yKVNeOFc7PCMGRw=
AllowedIPs = 10.10.0.2/32, 10.0.2.0/24
Endpoint = 10.0.0.3:51820

[Peer]
PublicKey = X4hZl/QUnQrIJua72c+4AhmXlrIthNFOk3j7M0qm2D4=
AllowedIPs = 10.10.0.3/32
Endpoint = 10.0.0.4:51820

[Peer]
PublicKey = zIEgpnqWPwwrv5wgcchN/Y3ejkSTAJhs4UFc0yjE0x4=
AllowedIPs = 10.10.0.4/32
