[Interface]
Address = 10.10.0.4/24
PrivateKey = oEacxdCFx78jBBU9OWcDtxenYTQJgMgKdlg1Kmd7alw=

[Peer]
PublicKey = QUGIicUMk85rghVtlsZdoiJE15Q4mRR32P7+KYkxWgE=
AllowedIPs = 10.0.1.0/24, 10.0.2.0/24, 10.10.0.0/24
Endpoint = 10.0.0.2:51820
PersistentKeepalive = 25
