[Interface]
Address = 10.10.0.2/24
PrivateKey = EDZ+3U2+TMJTTRfkbKxbZdKfwMrHkLq0VD8Z7ul0wGc=
ListenPort = 51820

[Peer]
PublicKey = QUGIicUMk85rghVtlsZdoiJE15Q4mRR32P7+KYkxWgE=
AllowedIPs = 10.10.0.1/32, 10.0.1.0/24, 10.10.0.3/32
Endpoint = 10.0.0.2:51820
PersistentKeepalive = 25
