[Interface]
Address = 10.10.0.3/24
PrivateKey = 8HjqDqoSnhncJHltqRRhUy453/cCgKupiRxilVIKCnA=
ListenPort = 51820

[Peer]
PublicKey = QUGIicUMk85rghVtlsZdoiJE15Q4mRR32P7+KYkxWgE=
AllowedIPs = 10.10.0.1/32, 10.0.1.0/24, 10.0.2.0/24
Endpoint = 10.0.0.2:51820
PersistentKeepalive = 25
