connections {
  main-far {
    local_addrs  = 10.0.0.2
    remote_addrs = 10.0.0.3
    local {
      auth = pubkey
      certs = main_cert.pem
      id = "CN=main.heig.ch, O=HEIG, C=CH"
    }
    remote {
      auth = pubkey
      id = "CN=far.heig.ch, O=HEIG, C=CH"
    }
    children {
      main-far {
        local_ts  = 10.0.1.0/24, 10.0.0.4/32
        remote_ts = 10.0.2.0/24
        start_action = trap
      }
    }
  }

  main-remote {
    local_addrs  = 10.0.0.2
    remote_addrs = 10.0.0.4
    local {
      auth = pubkey
      certs = main_cert.pem
      id = "CN=main.heig.ch, O=HEIG, C=CH"
    }
    remote {
      auth = pubkey
      id = "CN=remote.heig.ch, O=HEIG, C=CH"
    }
    children {
      main-remote {
        local_ts  = 10.0.1.0/24, 10.0.2.0/24
        remote_ts = 10.0.0.4/32
        start_action = trap
      }
    }
  }
}
