port 1194
proto udp
dev tun

ca   /root/openvpn/ca.crt
cert /root/openvpn/main.crt
key  /root/openvpn/main.key
dh   /root/openvpn/dh.pem

server 10.8.0.0 255.255.255.0

push "route 10.0.1.0 255.255.255.0"
push "route 10.0.2.0 255.255.255.0"
route 10.0.2.0 255.255.255.0

client-config-dir /root/openvpn/ccd
client-to-client

keepalive 10 120
persist-key
persist-tun
verb 3
